### ISSUE TITLE
deploy script requires stow to be in /usr/bin/stow and /bin/stow

### ISSUE THREAD

**Issue by dalyc** [ballmerpeak/dotfiles#2]
I think

<pre>
if [[ ! -x /usr/bin/stow ]] || [[ ! -x /bin/stow ]]; then
</pre>

should be 

<pre>
if [[ ! -x /usr/bin/stow ]] && [[ ! -x /bin/stow ]]; then
</pre>

**Comment by ballmerpeak** [comment]
Thanks for pointing this out. You are right, it should be using the AND operator instead of the OR operator. Because with the OR operator it will trigger the condition if /usr/bin/stow exists but /bin/stow doesn't (or vice-versa), which is definitely not want we intended. It's fixed now. Thanks again.
